Test notebook with fewer test cases
JuezUN/INGInious pull request #259
Opened 2020-12-10 02:59 UTC by crdgonzalezca

# Description

As in multilang the custom input is employed, here the students will be able to select up to 3 tests from the notebook and test the notebook without doing a new submission. This is supposed to leverage the server load as some submissions might be test through several tests.
 
Fixes #252 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

It was tested locally and everything looks perfect.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2020-12-17 18:07 UTC, Heldeg requested changes
Seem right. I am only concerned with the comment I left below; the other is just a suggestion.

2021-01-04 19:51 UTC, crdgonzalezca commented on inginious/frontend/plugins/multilang/problems/custom_input_notebook.py
> +    """
Can you please check this again? as I tested this on Firefox but it worked correctly.

2021-01-07 02:04 UTC, AndresFelipeCastellanos commented on inginious/frontend/plugins/multilang/problems/custom_input_notebook.py
> +    """
I tried to do the same with the notebook example in the test course and in another notebook task, but all the tests run regardless of which ones are selected.

2021-01-09 00:10 UTC, AndresFelipeCastellanos commented on inginious/frontend/plugins/multilang/problems/custom_input_notebook.py
> +    """
It's already working properly. Just need to update the changes made to the containers repository.

2021-01-09 00:13 UTC, AndresFelipeCastellanos approved these changes

2021-01-11 20:32 UTC, merged