Add Manual scoring plugin
JuezUN/INGInious pull request #269
Opened 2021-01-21 00:06 UTC by Heldeg

# Description

This is a correction about a previous PR named rubric scoring and another named Visualization merge PR. The PR adds a new plugin that allows for administrators evaluated the code of the students based on a rubric and to make comments for it.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

You need tasks with Notebook and multilang submissions type.
On course administration select manual scoring option. This display a list of the task.

- [x] Select a Notebook or multilang task, then a student and finally a submission. You should be able to see the code, the feedback cards, evaluated the code clicking the rubric, see the current score and add a comment. If you back to student's submissions list, you can see the grader, and if you go back to rubric scoring, you can see the comment.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-01-23 23:02 UTC, crdgonzalezca requested changes
Please check the comments. Though there are a lot, I think we are close.

2021-01-23 23:02 UTC, crdgonzalezca commented on inginious/frontend/plugins/manual_scoring/static/json/rubric_es.json
> +{
I don't see that this is used or is it? Otherwise try to load this json when the Spanish is the language of the user.

2021-01-23 23:03 UTC, crdgonzalezca requested changes
Please check the comments. Though there are a lot, I think we are close.

2021-02-11 16:48 UTC, Heldeg commented on inginious/frontend/plugins/manual_scoring/pages/api/user_submissions.py
> +        if "rubric_score" not in submission["custom"]:
Because not all submission have it

2021-02-12 02:26 UTC, Heldeg commented
I have a question. I use `message_box` , a js class for `contact_page` and `manual_scoring`. It is very Useful. Is it a good idea move that class to utils?

2021-02-13 23:12 UTC, crdgonzalezca commented
> I have a question. I use `message_box` , a js class for `contact_page` and `manual_scoring`. It is very Useful. Is it a good idea move that class to `utils`?

Yes, it is actually a good idea to have this class only in one place to avoid code repetition. I am just not sure how to manage. Probably having a separate `.js` and `.min.js` file for each class or utility, and the corresponding plugin (e.g. contact_page) loads this plugin.

However, to avoid mixing things up with this PR, and as the `contact_page` plugin is already in `master`, let's do that for a future PR where you make a proposal about how we will manage that, doing like a refactoring.

Though, it will help us a lot to organize the code. Good Idea

2021-02-14 00:03 UTC, crdgonzalezca requested changes
I see we are very close, just there are some few comments

2021-02-17 02:27 UTC, Heldeg commented on inginious/frontend/plugins/manual_scoring/static/json/rubric.json
> +{
Could you review the content of the rubric?

2021-02-17 20:05 UTC, crdgonzalezca requested changes
Some last changes in the Rubric as some errors were found.

2021-02-17 20:05 UTC, crdgonzalezca commented on inginious/frontend/plugins/manual_scoring/static/json/rubric_es.json
> +         "estructuras de datos":"Sin lógica."
First letter must be capitalized for all the keys in this file

2021-02-17 20:05 UTC, crdgonzalezca commented on inginious/frontend/plugins/manual_scoring/static/json/rubric_es.json
> +         "entendimiento del problema":"Se muestra una compresión muy básica o casi nula del problema."
```suggestion
         "entendimiento del problema":"Se muestra una comprensión muy básica o casi nula del problema."

```

2021-02-17 20:05 UTC, crdgonzalezca commented on inginious/frontend/plugins/manual_scoring/static/json/rubric_es.json
> +         "estrategia usada":"La solución no usa una aproximación adecuada. Puede ser usando fuerza bruta u otra aproximación que no funcione bien.\nNo se ve un propósito claro en el código y en la es
```suggestion
         "estrategia usada":"La solución no usa una aproximación adecuada. Puede ser usando fuerza bruta u otra aproximación que no funcione bien.\nNo se ve un propósito claro en el código y en la estrategia usada,  es difícil seguir la lógica del mismo."

```

2021-02-17 20:05 UTC, crdgonzalezca commented on inginious/frontend/plugins/manual_scoring/static/json/rubric_es.json
> +         "entendimiento del problema":"Se muestra una compresión parcial del problema a solucionar."
```suggestion
         "entendimiento del problema":"Se muestra una comprensión parcial del problema a solucionar."

```

2021-02-17 20:05 UTC, crdgonzalezca commented on inginious/frontend/plugins/manual_scoring/static/json/rubric_es.json
> +         "entendimiento del problema":"Muestra un entimiento completo del problema y su solucion tiene aceptada como veredicto."
```suggestion
         "entendimiento del problema":"Muestra un entimiento completo del problema y el veredicto de su solución es 'ACCEPTED'"

```

2021-02-18 03:33 UTC, crdgonzalezca approved these changes
LGTM!

2021-02-18 21:33 UTC, merged