Feature/ email registration on course for old users
JuezUN/INGInious pull request #374
Opened 2021-10-29 15:40 UTC by VirtualDiegox

# Description

This is a new feature that sends an email to old users when they're enrolled on a course.

Fixes #354 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- It was tested by checking the email of 3 accounts added via csv and verifing which email is received depending if the user is already registered or not

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2021-10-29 15:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/JuezUN/INGInious?pullRequest=374) <br/>All committers have signed the CLA.

2021-11-02 15:50 UTC, ferestrepoca requested changes

2021-11-02 15:50 UTC, ferestrepoca commented on inginious/frontend/i18n/es/LC_MESSAGES/messages.po
> +"cuales estas inscrito."
```suggestion
"cuales estás inscrito."
```

2021-11-02 15:50 UTC, ferestrepoca commented on inginious/frontend/i18n/es/LC_MESSAGES/messages.po
>  msgstr "En la barra superior, haga clic dónde su nombre se muestra."
```suggestion
msgstr "En la barra superior, haga clic donde se muestra su nombre."
```

2021-11-02 16:27 UTC, ferestrepoca approved these changes

2021-11-04 02:02 UTC, AndresFelipeCastellanos commented on inginious/frontend/plugins/register_students/pages/api/add_course_students_csv_file_api.py
> +        course_link = web.ctx.home + "/course/" + course.get_id() + "/"
```suggestion
        course_link = web.ctx.home + "/course/" + course.get_id()
```

Remove the last character from course_link url, as courses will not be found with it.

2021-11-04 02:09 UTC, AndresFelipeCastellanos commented on inginious/frontend/plugins/register_students/static/email_course_registration_template.html
> +        <h4>$:_("Hello {username}")</h4>
There is no need to translate the parameters in template, just translate text messages and leave the parameters outside the parentheses

2021-11-04 02:15 UTC, AndresFelipeCastellanos commented on inginious/frontend/plugins/register_students/static/email_course_registration_template.html
> +                <ul><li>$:_("{course_link}")</li></ul>
Leave this variable without the messages translation syntax. Also make sure to update de i18n files when change this and the above messages.

2021-11-04 02:18 UTC, AndresFelipeCastellanos commented on inginious/frontend/plugins/register_students/pages/api/add_course_students_csv_file_api.py
>          all_emails = []
Remove this variable as it is not used.

2021-11-04 02:28 UTC, AndresFelipeCastellanos requested changes
LGTM. There are some small comments.

2021-11-17 23:50 UTC, AndresFelipeCastellanos approved these changes

2021-11-18 20:35 UTC, merged