User manager retrieves using username AND email
JuezUN/INGInious pull request #423
Opened 2022-04-08 00:11 UTC by gaperezsa

# Description
User information retrieval in the User manager page was done using the username of the clicked user. This led to ill behavior when 2 or more users had the same username. Although 2 users with the same usernames is something that shouldn't happen, the recent incident of many empty string users allowed us to notice that the "first" user with an empty string as username would be retrieved no matter which of them was chosen.

Functions involved with the user retrieval were changed so that they also required and used the email along with the username. the respective MongoDB find sentence was changed and the "on-click" behavior was adapted so that the email is also sent when clicked.

Fixes #417 

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
3 instances of a user "juan" were inserted, the first 2 shared username while the first and the third shared email. This were inserted "Manually" into the local database for debugging purposes. Then, through the User Manager, all three instances were chosen to check behavior and the correct instance was retrieved in each case because; while they share email or username with another one, each is unique in their combination of username AND email.

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
![image](https://user-images.githubusercontent.com/56688374/162338828-0c103ed1-0c7e-40e5-8d73-72738deab55a.png)

2022-04-08 14:04 UTC, ferestrepoca requested changes
LGTM. Just a few code style suggestions and we're done. Thanks!

2022-04-08 14:04 UTC, ferestrepoca commented on inginious/frontend/plugins/user_management/pages/api/user_data.py
> +            user_data = self.get_user_data(username,email)
```suggestion
            user_data = self.get_user_data(username, email)
```

2022-04-08 14:04 UTC, ferestrepoca commented on inginious/frontend/plugins/user_management/pages/api/user_data.py
> +            user_original_info = self.get_user_data(username,email)
```suggestion
            user_original_info = self.get_user_data(username, email)
```

2022-04-08 14:04 UTC, ferestrepoca commented on inginious/frontend/plugins/user_management/pages/api/user_data.py
> +            user_final_info = self.get_user_data(new_username,email)
```suggestion
            user_final_info = self.get_user_data(new_username, email)
```

2022-04-21 17:16 UTC, VirtualDiegox approved these changes
LGTM!

2022-04-21 19:58 UTC, ferestrepoca approved these changes
LGTM. Thanks!

2022-04-21 19:58 UTC, merged